services:
  - type: web
    name: shopify-flask-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app.py:el-customer-profile"
    plan: free
    region: oregon
